# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intend < Formula
  desc "Compliance scanning CLI for Terraform and cloud infrastructure"
  homepage "https://github.com/intendcloud/intendcloud-platform"
  version "0.1.0"
  license "MIT"

  depends_on "checkov" => :optional
  depends_on "python3" => :optional

  on_macos do
    on_intel do
      url "https://github.com/intendcloud/intendcloud-platform/releases/download/v0.1.0/intendcloud-platform_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "3ee835db2f68af41d69f2d8b57d55a2b7877779f115bd3b1496b4247caf09518"

      def install
        bin.install "intend"
      end
    end
    on_arm do
      url "https://github.com/intendcloud/intendcloud-platform/releases/download/v0.1.0/intendcloud-platform_0.1.0_Darwin_arm64.tar.gz"
      sha256 "d43f696f8a231fce638c184e66eda39b71565fb79e435d25c68344bc430676e0"

      def install
        bin.install "intend"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/intendcloud/intendcloud-platform/releases/download/v0.1.0/intendcloud-platform_0.1.0_Linux_x86_64.tar.gz"
        sha256 "0b907aa77b2dfb0fc5ad3f24a02d56c55e45fba2578c56b9c9f17a4c54c4095b"

        def install
          bin.install "intend"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/intendcloud/intendcloud-platform/releases/download/v0.1.0/intendcloud-platform_0.1.0_Linux_arm64.tar.gz"
        sha256 "2d650f9e099608100edd643ac8b1deca930056f50bb9f932e16378f5691ed467"

        def install
          bin.install "intend"
        end
      end
    end
  end

  def caveats
    <<~EOS
      IntendCloud Audit CLI installed successfully!

      Quick Start:
        1. Install scanners (optional):
           pip3 install checkov

        2. Run your first audit:
           intend audit --terraform-dir ./my-terraform --frameworks cis-aws

      Documentation: https://github.com/intendcloud/intendcloud-platform

      Free Tier: CIS AWS v3.0.0 (full framework)
      Paid Tiers: SOC2, ISO 27001, PCI-DSS, NIST, DORA
    EOS
  end

  test do
    system "#{bin}/intend", "--version"
  end
end
