# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intend < Formula
  desc "Free compliance scanning CLI for Terraform and cloud infrastructure"
  homepage "https://github.com/intendcloud/intend"
  version "0.1.0"
  license "MIT"

  depends_on "checkov" => :optional
  depends_on "python3" => :optional

  on_macos do
    on_intel do
      url "https://github.com/intendcloud/intend/releases/download/v0.1.0/intend_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "b4727fedde459a9ac57926c2a254858edc57dac256a9e65a665c860aa33d2ea5"

      def install
        bin.install "intend"
      end
    end
    on_arm do
      url "https://github.com/intendcloud/intend/releases/download/v0.1.0/intend_0.1.0_Darwin_arm64.tar.gz"
      sha256 "c4d1c436ed1b164c8f72c1597e6eabfc889719f8298aedec51371cf38bfb6567"

      def install
        bin.install "intend"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/intendcloud/intend/releases/download/v0.1.0/intend_0.1.0_Linux_x86_64.tar.gz"
        sha256 "cc6d1973b54ae25031d272c5c8ebce7be972f2f5f827d018ab951bb2f992cab7"

        def install
          bin.install "intend"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/intendcloud/intend/releases/download/v0.1.0/intend_0.1.0_Linux_arm64.tar.gz"
        sha256 "1e898348e229697dae46109016a5eb5ed6938404d7124e1cb52bc5e627a7b71e"

        def install
          bin.install "intend"
        end
      end
    end
  end

  def caveats
    <<~EOS
      IntendCloud Audit CLI installed successfully!

      Quick Start:
        1. Install scanners (optional):
           pip3 install checkov

        2. Run your first audit:
           intend audit --terraform-dir ./my-terraform --frameworks cis-aws

      Documentation: https://github.com/intendcloud/intend

      Free Tier: CIS AWS, Azure, GCP (full frameworks)
      Enterprise Platform: https://intendcloud.com
    EOS
  end

  test do
    system "#{bin}/intend", "--version"
  end
end
